const users = [
    { email: 'user1@example.com', password: '1234567' },
    { email: 'user2@example.com', password: 'password456' },
    { email: 'user3@example.com', password: 'password789' },
    { email: 'user4@example.com', password: 'password101' },
    { email: 'user5@example.com', password: 'password202' },
    { email: 'user6@example.com', password: 'password303' },
    { email: 'user7@example.com', password: 'password404' },
    { email: 'user8@example.com', password: 'password505' },
    { email: 'user9@example.com', password: 'password606' },
    { email: 'user10@example.com', password: 'password707' },
    { email: 'user11@example.com', password: 'password808' },
    { email: 'user12@example.com', password: 'password909' },
    { email: 'user13@example.com', password: 'password010' },
    { email: 'user14@example.com', password: 'password111' },
    { email: 'user15@example.com', password: 'password212' },
    { email: 'user16@example.com', password: 'password313' },
    { email: 'user17@example.com', password: 'password414' },
    { email: 'user18@example.com', password: 'password515' },
    { email: 'user19@example.com', password: 'password616' },
    { email: 'user20@example.com', password: 'password717' },
    { email: 'user21@example.com', password: 'password818' },
    { email: 'user22@example.com', password: 'password919' },
    { email: 'user23@example.com', password: 'password020' },
    { email: 'user24@example.com', password: 'password121' },
    { email: 'user25@example.com', password: 'password222' },
    { email: 'user26@example.com', password: 'password323' },
    { email: 'user27@example.com', password: 'password424' },
    { email: 'user28@example.com', password: 'password525' },
    { email: 'user29@example.com', password: 'password626' },
    { email: 'user30@example.com', password: 'password727' },
    { email: 'user31@example.com', password: 'password828' },
    { email: 'user32@example.com', password: 'password929' },
    { email: 'user33@example.com', password: 'password030' },
    { email: 'user34@example.com', password: 'password131' },
    { email: 'user35@example.com', password: 'password232' },
    { email: 'user36@example.com', password: 'password333' },
    { email: 'user37@example.com', password: 'password434' },
    { email: 'user38@example.com', password: 'password535' },
    { email: 'user39@example.com', password: 'password636' },
    { email: 'user40@example.com', password: 'password737' },
    { email: 'user41@example.com', password: 'password838' },
    { email: 'user42@example.com', password: 'password939' },
    { email: 'user43@example.com', password: 'password040' },
    { email: 'user44@example.com', password: 'password141' },
    { email: 'user45@example.com', password: 'password242' },
    { email: 'user46@example.com', password: 'password343' },
    { email: 'user47@example.com', password: 'password444' },
    { email: 'user48@example.com', password: 'password545' },
    { email: 'user49@example.com', password: 'password646' },
    { email: 'user50@example.com', password: 'password747' },
  ];
  
  export default users;
  